name: smartprescription
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  file_picker: ^10.1.9
  image_picker: ^1.1.2
  pdf: ^3.10.4
  path_provider: ^2.1.1
  open_file: ^3.3.2
  permission_handler: ^12.0.0+1
  fl_chart: ^1.0.0
  qr_code_scanner_plus: ^2.0.10+1
  intl: ^0.19.0
  provider: ^6.1.5
  flutter_pdfview: ^1.4.1+1
  flutter_local_notifications: ^19.3.0
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/icons/drug.png
    - assets/icons/allergy.png
    - assets/icons/blood.png
    - assets/icons/chronic.png
    - assets/icons/examin.png
    - assets/icons/presc.png
    - assets/icons/vacc.png
